## --- MANDATORY ---
user: 'your_username'
password: 'your_password'

## --- OPTIONAL --- (delete if default wanted)

# Time in seconds between each check
refresh_rate: 30

# Blacklist projects
blacklist:
  - 'Old-LibftASM'
  - 'ft_ls'

# By default, snipe any slots matching restrictions between today and today + 5 days
span: 5

# By default, restrict slots between 08:00 and 18:00 
default: { start: '08:00', end: '18:00' }

# Here are some examples of specific rules to overwrite the default ones
mon:
  - { start: '12:00', end: '18:00' }

tue:
  - { start: '08:00', end: '12:00' }
  - { start: '15:00', end: '18:00' }


# TODO: NOT IMPLEMENTED YET
# Custom ranges, using the ISO 8601 format
# WARNING: will take ANY slots between specified ranges, use with caution
custom:
  - { start: 2020-12-14T08:30:00, end: 2020-12-14T10:00:00 }